### ISSUE TITLE
ValueError: Number of samples, -9223372036854775808, must be non-negative.

### ISSUE THREAD

**Issue by bpinsard** [poldracklab/fitlins#248] opened 2020-07-31 13:21 UTC
I am getting the following crash, and I am not sure if is more a pybids or fitlins issue.

```
Captured warning (<class 'RuntimeWarning'>): divide by zero encountered in double_scalars
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/fitlins", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py", line 272, in main
    sys.exit(run_fitlins(sys.argv[1:]))
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py", line 264, in run_fitlins
    analysis.setup(**selectors)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 94, in setup
    b.setup(input_nodes, drop_na=drop_na, **selectors)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 228, in setup
    coll = apply_transformations(coll, self.transformations)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 568, in apply_transformations
    func(collection, cols, **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/transformations/base.py", line 
88, in __new__
    return t.transform()
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/transformations/base.py", line 
262, in transform
    result = self._transform(data[i], **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/transformations/compute.py", li
ne 77, in _transform
    oversampling=oversampling
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/hrf.py", line 456, in compute_r
egressor
    exp_condition, frame_times, oversampling, min_onset)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/hrf.py", line 242, in _sample_c
ondition
    np.rint(n_hr).astype(np.int))
  File "<__array_function__ internals>", line 6, in linspace
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/numpy/core/function_base.py", line 130, in li
nspace
    raise ValueError("Number of samples, %s, must be non-negative." % num)
ValueError: Number of samples, -9223372036854775808, must be non-negative.
```

**Comment by effigies** [comment] 2020-07-31 14:16
Huh. Actually looks like it might be a bug in the HRF code we lifted from nistats. Do you have data we can reproduce with?

**Comment by bpinsard** [comment] 2020-07-31 14:29
What minimal set of file would you need?
The full dataset is under a DTA that is yet WIP and is also very large.
Also I have no info on which subject/session/run crashes.

Basically we used emotion task from HCP.

Maybe my model is wrong:

```
{
  "Name": "hcptrt_emotion",
  "Description": "fit emotion model",
  "Input": {
    "task": "emotion"
  },
  "Steps": [
    {
      "Level": "run",
      "Transformations": [
        {
          "Name": "Factor",
          "Input": ["trial_type"]
        },
        {
          "Name": "Convolve",
          "Input": [
            "trial_type.response_shape",
            "trial_type.response_face"
          ]
        }
      ],
      "Model": {
        "X": [
          "trial_type.response_shape",
          "trial_type.response_face",
          "framewise_displacement",
          "trans_x", "trans_y", "trans_z", "rot_x", "rot_y", "rot_z",
          "a_comp_cor_00", "a_comp_cor_01", "a_comp_cor_02",
          "a_comp_cor_03", "a_comp_cor_04", "a_comp_cor_05"
        ]
      },
      "DummyContrasts": {
        "Type": "t"
      }
    },
    {
      "Level": "subject",
      "DummyContrasts": {
        "Type": "t"
      }
    },
    {
      "Level": "dataset",
      "DummyContrasts": {
        "Type": "t"
      }
    }
  ]
}
```

and the events looks like:

```
trial_type      nbloc   onset   duration        ntrial  stim_file_top   stim_file_left  stim_file_right answer  co
rrect_answer    response_time   countdown_stim
countdown               0.0     1.984                                                           4
countdown               2.0     1.984                                                           3
countdown               4.0     1.984                                                           2
countdown               6.0     1.984                                                           1
new_bloc_shape  1.0     8.017   2.983
response_shape  1.0     11.0    1.189   1       emotion/oval-horizontal.bmp     emotion/oval-horizontal.bmp     em
otion/oval-vertical.bmp left    left    1.189
response_shape  1.0     14.016  0.757   2       emotion/oval-vertical.bmp       emotion/oval-horizontal.bmp     em
otion/oval-vertical.bmp right   right   0.757
response_shape  1.0     17.033  0.8     3       emotion/circle.bmp      emotion/circle.bmp      emotion/oval-verti
cal.bmp left    left    0.8
response_shape  1.0     20.049  0.622   4       emotion/oval-vertical.bmp       emotion/circle.bmp      emotion/ov
al-vertical.bmp right   right   0.622
response_shape  1.0     23.066  1.174   5       emotion/circle.bmp      emotion/oval-horizontal.bmp     emotion/ci
rcle.bmp        right   right   1.174
response_shape  1.0     26.082  0.837   6       emotion/oval-horizontal.bmp     emotion/oval-horizontal.bmp     em
otion/circle.bmp        left    left    0.837
new_bloc_face   2.0     29.115  2.983
response_face   2.0     32.098  0.92    1       emotion/FA1_top.jpg     emotion/FA1_left.jpg    emotion/FA1_right.
jpg     left    left    0.92
response_face   2.0     35.115  1.208   2       emotion/MF1_top.jpg     emotion/MF1_left.jpg    emotion/MF1_right.
jpg     left    left    1.208
response_face   2.0     38.132  1.496   3       emotion/MA1_top.jpg     emotion/MA1_left.jpg    emotion/MA1_right.
jpg     right   right   1.496
response_face   2.0     41.148  1.444   4       emotion/FF1_top.jpg     emotion/FF1_left.jpg    emotion/FF1_right.
jpg     right   right   1.444
response_face   2.0     44.165  1.287   5       emotion/FA2_top.jpg     emotion/FA2_left.jpg    emotion/FA2_right.
jpg     right   right   1.287
response_face   2.0     47.181  1.756   6       emotion/MA2_top.jpg     emotion/MA2_left.jpg    emotion/MA2_right.
jpg     right   right   1.756
new_bloc_shape  3.0     50.214  2.983
.... 
```

**Comment by effigies** [comment] 2020-08-05 00:13
After starting up FitLins, there should be a database file. If you didn't set it, it should be in the scratch directory. In IPython, I would do:

```Python
%pdb
from bids import BIDSLayout
from bids.analysis import Analysis
layout = BIDSLayout.load('/path/to/bids_cache')
analysis = Analysis(layout, model_path)
analysis.setup()
```

If you have a system I could login to, to play with the data, I can try to track this down. I really don't have great ideas apart from open the debugger and see what I can find.

**Comment by bpinsard** [comment] 2020-08-05 01:46
Thanks for the pointer and commands for debugging in a simpler setting.
It looks that it's caused by zero duration of event that cause hrf oversampling to be infinite. These are likely a problem with the eprime conversion.

**Comment by effigies** [comment] 2020-08-05 01:53
Nah, this is a bug in pybids. Zero duration events are valid in BIDS.

**Comment by effigies** [comment] 2020-11-19 22:37
This should be fixed.

**Closed by effigies** 2020-11-19 22:37 UTC
